//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySpecsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADD_TO_CART
    {
        public int SPECS_ID { get; set; }
        public string SPECS_NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<double> SPECS_PRICE { get; set; }
        public string EMAILID { get; set; }
    
        public virtual SPECS_DETAILS SPECS_DETAILS { get; set; }
        public virtual USERREGISTER USERREGISTER { get; set; }
    }
}
