//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySpecsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOGINADMIN
    {
        [Required(ErrorMessage = "USER NAME is required")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "PASSWORD is required")]
        public string PASSWORD { get; set; }
        public string ROLE { get; set; }
    }
}
