//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySpecsProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineSpecsDetailsEntities : DbContext
    {
        public OnlineSpecsDetailsEntities()
            : base("name=OnlineSpecsDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOGINADMIN> LOGINADMINs { get; set; }
        public virtual DbSet<ORDER_DETAILS> ORDER_DETAILS { get; set; }
        public virtual DbSet<SPECS_DETAILS> SPECS_DETAILS { get; set; }
        public virtual DbSet<USERREGISTER> USERREGISTERs { get; set; }
        public virtual DbSet<ADD_TO_CART> ADD_TO_CART { get; set; }
    }
}
