//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySpecsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USERREGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERREGISTER()
        {
            this.ADD_TO_CART = new HashSet<ADD_TO_CART>();
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
        }
        [Required(ErrorMessage ="First name is required")]
        [DisplayName("USERNAME")]
        public string FIRSTNAME { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        public string LASTNAME { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public string GENDER { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string ADDRESS { get; set; }
        [Required(ErrorMessage = "Pin code is required")]
        public Nullable<int> PINCODE { get; set; }
        [Required(ErrorMessage = "Mobile number is required")]
        public string MOBILENUMBER { get; set; }
        [Required(ErrorMessage = "Email Id is required")]
        public string EMAILID { get; set; }
        [Required(ErrorMessage = "Password is required")]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "Compare password is required")]
        [NotMapped]
        [CompareAttribute("PASSWORD",ErrorMessage ="Password do not match")]
        public string CONFIRMPASSWORD { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADD_TO_CART> ADD_TO_CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
    }
}
